# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e23f4026b3d04d144b72b8c597673639b01cff9892085382713d45f59f170d963a8eaab12e280f53aed134d2b8ae0aeb17e83c33d0faaf81586598a72d6bd108
  tumblr_consumer_key: <%= ENV["TUMBLR_CONSUMER_KEY"] %>
  tumblr_consumer_secret: <%= ENV["TUMBLR_CONSUMER_SECRET"] %>
  oauth_token: <%= ENV["OAUTH_TOKEN"] %>
  oauth_secret: <%= ENV["OAUTH_SECRET"] %>

test:
  secret_key_base: 2a073ca6a6fef21936ce15ba41b718eb50d9694e1c6c6f392872cf6c991d54ee11edddfdbe4ea4d215c5258b25cc72593f350ec845fd4be6a8c25d34fbf7ec67
  tumblr_consumer_key: <%= ENV["TUMBLR_CONSUMER_KEY"] %>
  tumblr_consumer_secret: <%= ENV["TUMBLR_CONSUMER_SECRET"] %>
  oauth_token: <%= ENV["OAUTH_TOKEN"] %>
  oauth_secret: <%= ENV["OAUTH_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tumblr_consumer_key: <%= ENV["TUMBLR_CONSUMER_KEY"] %>
  tumblr_consumer_secret: <%= ENV["TUMBLR_CONSUMER_SECRET"] %>
  oauth_token: <%= ENV["OAUTH_TOKEN"] %>
  oauth_secret: <%= ENV["OAUTH_SECRET"] %>